# Generated by Django 3.2.8 on 2021-10-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('blocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0, upload_to='img/blocks/')),
                ('SX', models.IntegerField(default=40)),
                ('SY', models.IntegerField(default=40)),
                ('EX', models.IntegerField(default=40)),
                ('EY', models.IntegerField(default=40)),
                ('no_of_blocks', models.IntegerField(default=1)),
                ('block_text', models.CharField(default='e', max_length=140)),
                ('twitter', models.TextField(default='e')),
                ('discord', models.TextField(default='e')),
                ('instagram', models.TextField(default='e')),
                ('telegram', models.TextField(default='e')),
                ('website', models.TextField(default='e')),
                ('status', models.BooleanField(default=False)),
                
            ],
        ),
    ]
