# Generated by Django 3.1 on 2021-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211026_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_no',
            field=models.IntegerField(default=0),
        ),
    ]
